# Generated by Django 3.0.5 on 2020-05-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200505_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ['-posted_at']},
        ),
    ]
