# Generated by Django 3.0.5 on 2020-05-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
