export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const STALK_USER = "STALK_USER"
export const STALK_LOADING = "STALK_LOADING"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_FAIL = "POST_FAIL"
export const UPDATED_USER = "UPDATED_USER"
export const UPDATING_USER = "UPDATING_USER"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"
export const UPDATED_PASSWORD = "UPDATED_PASSWORD"
export const UPDATING_PASSWORD = "UPDATING_PASSWORD"
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR"
export const SENDING_FOLLOW_REQUEST = "SENDING_FOLLOW_REQUEST"
export const REQUEST_SENT_SUCCESFULL = "REQUEST_SENT_SUCCESFULL"
export const REQUEST_SENT_ERROR = "REQUEST_SENT_ERROR"
export const POSTING_COMMENT = "POSTING_COMMENT"
export const COMMENT_POSTED = "COMMENT_POSTED"
export const COMMENT_ERROR = "COMMENT_ERROR"
export const RETRIEVING_COMMENTS = "RETRIEVING_COMMENTS"
export const COMMENTS_RETRIEVED = "COMMENTS_RETRIEVED"
export const RETRIEVING_SEARCH_USERS = "RETRIEVING_SEARCH_USERS"
export const SEARCH_USERS_RETRIEVED = "SEARCH_USERS_RETRIEVED"
export const RETRIEVING_SEARCH_POSTS = "RETRIEVING_SEARCH_POSTS"
export const SEARCH_POSTS_RETRIEVED = "SEARCH_POSTS_RETRIEVED"











