export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const STALK_USER = "STALK_USER"
export const STALK_LOADING = "STALK_LOADING"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const FEED_LOADING = "FEED_LOADING"
export const FEED_LOADED = "FEED_LOADED"
export const FEED_ERROR = "FEED_ERROR"
export const MAINFEED_LOADING = "MAINFEED_LOADING"
export const MAINFEED_LOADED = "MAINFEED_LOADED"
export const MAINFEED_ERROR = "MAINFEED_ERROR"
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_FAIL = "POST_FAIL"




