# Generated by Django 3.0.5 on 2020-05-06 05:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_friends'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('user1', 'user2')},
        ),
    ]
