# Generated by Django 3.0.5 on 2020-05-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_follows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'ordering': ['-timestamp']},
        ),
    ]
