# Generated by Django 3.0.5 on 2020-05-08 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20200508_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='user2',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='user1',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('user_id', 'following_user_id')},
        ),
    ]
